-- Disable foreign key checks to allow truncation of tables with foreign keys
ALTER TABLE Apprentice NOCHECK CONSTRAINT ALL;
ALTER TABLE Practitioner NOCHECK CONSTRAINT ALL;
ALTER TABLE Master NOCHECK CONSTRAINT ALL;
ALTER TABLE [Rank] NOCHECK CONSTRAINT ALL;
ALTER TABLE Item NOCHECK CONSTRAINT ALL;

-- Truncate all tables
TRUNCATE TABLE Apprentice;
TRUNCATE TABLE Practitioner;
TRUNCATE TABLE Master;
TRUNCATE TABLE [Rank];
TRUNCATE TABLE Item;
TRUNCATE TABLE Ninja;

-- Re-enable foreign key checks
ALTER TABLE Apprentice CHECK CONSTRAINT ALL;
ALTER TABLE Practitioner CHECK CONSTRAINT ALL;
ALTER TABLE Master CHECK CONSTRAINT ALL;
ALTER TABLE [Rank] CHECK CONSTRAINT ALL;
ALTER TABLE Item CHECK CONSTRAINT ALL;
